CREATE TABLE humans (
  `id` mediumint(8) unsigned NOT NULL auto_increment, 
  `firstname` varchar(255) default NULL,
  `lastname` varchar(255) default NULL,
  `email` varchar(255) default NULL,
  `address_street` varchar(255) default NULL,
  `address_city` varchar(50) default NULL,
  `address_state` varchar(50) default NULL,
  `address_zip` varchar(10) default NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1; 


INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('1','Hu','Rasmussen','ut.erat@nondui.ca','Ap #697-4926 Pretium St.','Pittsfield','IN','74933');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('2','Kyle','Salas','faucibus@diamProindolor.org','P.O. Box 713, 8716 Nec Road','Charlotte','California','15452');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('3','Wing','Stevens','facilisi.Sed.neque@loremluctus.edu','Ap #813-7393 Feugiat. Rd.','Westlake Village','Missouri','86178');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('4','Ferris','Sheppard','egestas.Fusce.aliquet@ligulaNullamfeugiat.com','482-4785 Sed Rd.','Oneida','Oklahoma','35805');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('5','Grady','Mcdaniel','pharetra@ipsumdolor.ca','156-4243 Nonummy. Rd.','Gulfport','South Carolina','42999');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('6','Amanda','Monroe','semper.cursus.Integer@acrisusMorbi.ca','704-308 Ultrices Av.','Birmingham','South Carolina','33487');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('7','Iris','Mcmahon','elit.Curabitur@quam.ca','P.O. Box 626, 5830 Nunc, Av.','Brookings','WA','82383');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('8','Jayme','Morris','metus.In@laoreet.com','Ap #501-595 Iaculis, Rd.','Placentia','Vermont','67028');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('9','Linus','Cooley','luctus.lobortis.Class@non.org','P.O. Box 555, 9702 Magna, Rd.','Thiensville','PA','28835');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('10','Fallon','Conway','Suspendisse@Loremipsumdolor.ca','420-7071 Quis Av.','Norwalk','Texas','32731');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('11','Edan','Burke','ante@Nuncmauris.com','8728 Curabitur Ave','Woodruff','Pennsylvania','98725');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('12','Halla','Morse','Proin.non@dolorNullasemper.ca','P.O. Box 924, 2488 Consectetuer St.','Irving','NM','23813');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('13','Hoyt','Valenzuela','tempus@DonecnibhQuisque.com','7502 Enim. Rd.','Williamsburg','New York','28410');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('14','Stella','Reid','dui.Fusce.aliquam@purusaccumsaninterdum.ca','P.O. Box 183, 813 Dis St.','Hot Springs','Virginia','00170');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('15','Maryam','Hanson','malesuada.id.erat@anteblandit.com','630-4782 Tellus Ave','Scarborough','MS','67161');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('16','Alfonso','Mckenzie','Vivamus.euismod@urnaNunc.org','P.O. Box 765, 5887 Euismod Av.','Cypress','ID','00848');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('17','Conan','Weaver','lectus.pede@felisNulla.com','Ap #890-9350 Risus. Street','Sunnyvale','NY','46508');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('18','Xantha','Dunn','Nulla.interdum@ante.ca','P.O. Box 728, 8562 Elit Road','Madison','Arizona','35424');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('19','Troy','Ware','nulla.vulputate.dui@facilisisnon.com','677-7488 Feugiat Street','Las Cruces','Indiana','66352');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('20','Maile','Mcbride','eu@Nullamvitaediam.org','Ap #264-9799 Dolor St.','Evansville','MD','69533');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('21','Joel','Norton','rhoncus.id.mollis@etipsum.com','P.O. Box 518, 177 Mollis Av.','Fort Wayne','RI','94897');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('22','Hanna','Frederick','facilisis.eget@nislsemconsequat.ca','118-5030 Et, Rd.','Malibu','AK','81784');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('23','Brock','Mejia','odio.Etiam@Pellentesqueut.org','7641 Eu Rd.','Texarkana','OK','07502');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('24','Bertha','Hudson','consequat@turpisvitaepurus.com','Ap #612-6211 Ut St.','Berlin','District of Columbia','64933');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('25','Cynthia','Bowers','non.bibendum@ante.edu','P.O. Box 713, 8054 Faucibus Rd.','Decatur','West Virginia','91452');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('26','Pearl','Prince','lobortis@faucibusid.org','8133 At Avenue','Johnstown','West Virginia','11389');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('27','Linus','Elliott','eget.metus.In@erat.com','Ap #325-2042 Lorem, Rd.','Rhinelander','Nebraska','23407');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('28','Myra','Barrett','ut.pharetra@et.com','3687 Risus. Rd.','Joliet','MN','97829');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('29','Mannix','Cervantes','arcu.imperdiet@Etiamligulatortor.com','P.O. Box 846, 9018 Mollis Av.','Minneapolis','CT','26051');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('30','Bethany','Baxter','a.facilisis@a.com','3969 Posuere St.','Nome','CO','22401');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('31','Ahmed','Stone','Duis@euismod.ca','1919 Arcu. St.','Cicero','NJ','94688');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('32','Edan','Santiago','lobortis.ultrices.Vivamus@dictum.ca','P.O. Box 631, 1577 Elit, Street','Joliet','DC','20542');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('33','Stella','Bailey','est.Mauris@tristiquesenectuset.edu','657-5825 Quisque Rd.','Anderson','Pennsylvania','01915');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('34','Merrill','Giles','dictum.placerat@imperdietdictum.ca','Ap #124-2797 Dui Av.','Atlanta','Connecticut','74334');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('35','Cailin','Buckner','Fusce.aliquam@non.com','P.O. Box 698, 6157 Penatibus St.','Fort Wayne','Georgia','07237');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('36','Daphne','Holt','at.lacus.Quisque@per.com','Ap #712-1328 Arcu. Ave','Anchorage','North Dakota','74837');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('37','Anthony','Mccarty','justo.eu.arcu@etrutrum.org','3874 Leo. Road','Corpus Christi','NJ','11782');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('38','Rinah','Nicholson','Nulla.facilisi.Sed@IncondimentumDonec.org','726-6840 Non, St.','Fitchburg','IA','22364');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('39','Cheyenne','Davis','est.Nunc.laoreet@Nuncsed.edu','P.O. Box 906, 3024 Orci Road','Des Moines','Alabama','13076');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('40','Amela','Brock','amet.nulla@congueIn.ca','P.O. Box 292, 511 Sit St.','Muskogee','CA','48770');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('41','Irma','Prince','dui.in.sodales@Duismienim.ca','7641 Fermentum Avenue','Lakewood','Colorado','13634');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('42','Dara','Vang','orci.lobortis@felisadipiscingfringilla.ca','9130 Lorem Rd.','Houston','Oklahoma','59146');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('43','Mariko','Vincent','scelerisque.neque.sed@lectussit.edu','Ap #359-1465 Pede. St.','Charlotte Amalie','Vermont','37121');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('44','Alisa','Williams','eu.dolor@Cumsociis.com','P.O. Box 900, 8011 Sem St.','Truth or Consequences','Ohio','97609');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('45','Wyoming','Walton','augue@Donec.com','588-3368 Ut Avenue','Muncie','NC','60949');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('46','Clementine','Castillo','rutrum@sem.edu','P.O. Box 167, 8213 Diam Av.','Fremont','NJ','59485');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('47','Kirby','Kim','et.rutrum@pretium.com','Ap #796-6411 At Rd.','Dunkirk','MO','25018');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('48','Indigo','Parks','Integer.urna@felis.ca','604-6510 Diam. St.','Yakima','Illinois','81144');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('49','Wilma','West','Nunc.sollicitudin.commodo@neque.ca','158-7735 Aliquet Street','Santa Clarita','IL','30990');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('50','Madaline','Dodson','eu.euismod@Donec.edu','P.O. Box 543, 243 Mauris St.','West Warwick','Massachusetts','63141');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('51','Jade','Perkins','risus.Duis.a@Cras.org','344-5578 Tincidunt St.','Eugene','IN','43343');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('52','Bo','Summers','lacus@montesnascetur.com','7509 Urna. Av.','Reedsport','SC','86602');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('53','Virginia','Hooper','arcu.Nunc@non.org','7938 Montes, Rd.','Gilette','AL','39826');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('54','Kylee','Suarez','consequat.nec@ultrices.ca','P.O. Box 844, 8467 Pede Road','Peru','District of Columbia','81764');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('55','Yoko','Moran','Nunc.ac@sit.org','248-4739 Mauris. Avenue','McAllen','Rhode Island','16103');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('56','Cole','Cole','Sed@dictum.org','Ap #367-9591 Fermentum Rd.','Moorhead','Illinois','26771');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('57','Cassidy','Kelley','luctus.sit@ornareInfaucibus.org','8914 Orci, Rd.','New Kensington','VA','53083');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('58','Melyssa','Craft','Lorem.ipsum@atfringillapurus.org','7809 Nulla. Rd.','Altoona','HI','73252');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('59','Tatum','Erickson','magna@Etiamligulatortor.ca','490-8555 Lorem Rd.','Sturgis','ND','22702');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('60','Chester','Fitzpatrick','et.eros.Proin@non.edu','P.O. Box 891, 8013 Proin Rd.','Pine Bluff','New Hampshire','20708');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('61','Charlotte','Reed','eu.elit@ipsum.edu','P.O. Box 459, 8943 Egestas Avenue','Baytown','Georgia','82969');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('62','Kato','Clarke','scelerisque.neque@blanditviverra.org','2370 Purus, Rd.','Bethany','Illinois','38277');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('63','Emerald','Dorsey','risus.Donec.nibh@quam.ca','Ap #825-4958 Non Street','Holyoke','VT','35156');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('64','Brielle','Sparks','vitae.purus@sociis.com','Ap #341-9510 Etiam St.','Compton','North Carolina','96640');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('65','Genevieve','Gray','dolor@luctusetultrices.org','1845 Enim, Road','Tyler','Massachusetts','42072');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('66','Eden','Foster','velit.Cras.lorem@nunc.ca','P.O. Box 287, 7042 Nulla Road','Claremore','Massachusetts','73492');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('67','Jarrod','Gates','Suspendisse.commodo@Vestibulumanteipsum.ca','804-8395 Lobortis Avenue','Littleton','OK','04076');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('68','Stephen','Church','porttitor.interdum@Namnullamagna.ca','239-5357 Sed St.','Downey','IL','24109');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('69','Callum','Rasmussen','mi.Duis@loremegetmollis.edu','7277 Turpis Rd.','Blacksburg','NY','40565');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('70','Sarah','Lloyd','at.egestas.a@Crasconvallisconvallis.org','355-8232 Sapien. St.','Tallahassee','New Mexico','13183');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('71','Jameson','Levy','velit.Aliquam@dignissimMaecenasornare.com','P.O. Box 229, 7667 Justo Avenue','Charlottesville','SC','81560');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('72','Quail','Fox','a.malesuada.id@turpisegestas.edu','Ap #919-8131 Aliquam Rd.','Fort Dodge','FL','16688');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('73','Pandora','Ortega','et.libero@quispede.com','P.O. Box 583, 4209 Phasellus Rd.','Eden Prairie','MS','90373');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('74','Clarke','Weaver','quis.urna.Nunc@Proin.com','P.O. Box 709, 9765 Dolor Rd.','Bellflower','New Mexico','27960');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('75','Adrienne','Chandler','egestas.urna@nibh.org','8246 Metus. Av.','Port St. Lucie','Virginia','87057');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('76','Caryn','Rush','quam.dignissim@penatibus.org','Ap #347-4908 Ad Street','Ypsilanti','New Jersey','42229');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('77','Unity','Cooper','enim@dui.edu','P.O. Box 527, 2668 Nec Av.','Texarkana','VA','29279');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('78','William','Frazier','velit.dui@disparturientmontes.org','Ap #344-9962 Aliquet Ave','Laguna Hills','Colorado','96525');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('79','Demetria','Carr','id.risus.quis@malesuadafames.org','458-1899 Metus. Av.','Shreveport','TX','50555');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('80','Tana','Moreno','Maecenas.mi.felis@elitpede.com','Ap #113-877 Ultrices. St.','Westlake Village','WA','79888');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('81','Anika','Ray','Quisque@parturient.ca','Ap #520-8192 Varius Av.','Norwalk','MI','68967');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('82','Gregory','Mcpherson','erat@risus.org','9643 Euismod St.','Hartford','IL','05653');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('83','Destiny','Moran','Maecenas.iaculis.aliquet@lacusNulla.edu','9385 Non St.','Perth Amboy','Rhode Island','52521');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('84','Tucker','Gordon','cursus.diam@vel.edu','Ap #221-7159 Metus. St.','Fort Wayne','Iowa','87684');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('85','Rowan','Mclaughlin','molestie.orci@tincidunt.ca','Ap #761-3571 Egestas Avenue','Guthrie','UT','90963');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('86','Joseph','Wilkinson','eu@egestasSedpharetra.ca','Ap #358-8043 Donec Street','Sunnyvale','Montana','44578');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('87','Judith','Munoz','aliquet@velitdui.com','2464 Nostra, Ave','Placentia','Colorado','78306');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('88','Dean','Hurst','diam@magna.com','P.O. Box 321, 329 Sed Road','Manhattan Beach','New Mexico','85812');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('89','Shaeleigh','Dean','mauris.id.sapien@Donec.edu','587-4095 Tincidunt Street','Dallas','Wyoming','38733');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('90','Hanna','Alford','lacus@necmetusfacilisis.edu','P.O. Box 335, 7903 Risus. St.','Oklahoma City','Maryland','69801');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('91','Michael','Barker','mauris.sit.amet@ligulaelit.ca','809-1618 Eget, Avenue','Pico Rivera','VA','98975');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('92','Demetria','Burks','nulla@Suspendissealiquetsem.org','P.O. Box 859, 501 Elit Street','Hartford','New Mexico','56863');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('93','Joshua','Mercer','non@quisturpis.edu','456-9302 Risus. Ave','Beacon','Arkansas','37841');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('94','Amos','Arnold','fames.ac@Aeneanmassa.ca','894-7821 Per Rd.','Mount Vernon','Washington','62153');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('95','Dominic','Mueller','Phasellus.ornare.Fusce@id.edu','P.O. Box 492, 2057 Integer Ave','Chicago Heights','KY','84160');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('96','Leigh','Matthews','justo.eu.arcu@libero.com','Ap #502-2738 Vitae Road','Urbana','VT','60382');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('97','Farrah','Clements','rutrum@sed.org','314-4667 Lacus Rd.','New Albany','Montana','87716');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('98','Carla','Becker','quam.elementum@erategettincidunt.com','Ap #755-908 Libero. Av.','Durango','OR','42688');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('99','Brianna','Hampton','ligula.Aliquam.erat@urna.edu','P.O. Box 536, 8073 Massa. Street','Evanston','Massachusetts','23435');
INSERT INTO `humans` (`id`,`firstname`,`lastname`,`email`,`address_street`,`address_city`,`address_state`,`address_zip`) VALUES ('100','Cyrus','Bonner','Etiam.bibendum@fermentumrisus.com','758-6274 Ac Ave','Shamokin','Idaho','41924');